version: '3.8'
services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    networks:
      - integracioncontinuadocker
  backend:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 3000:3000
    networks:
      - integracioncontinuadocker
networks:
  integracioncontinuadocker:
    driver: bridge